// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {state} from '../models';
import {thumb} from '../models';
import {tree} from '../models';
import {imgread} from '../models';

export function GetState():Promise<state.StateData>;

export function GetThumbnail(arg1:string,arg2:number,arg3:string):Promise<thumb.Result>;

export function ListDirectory(arg1:string):Promise<Array<tree.Node>>;

export function OpenFolderDialog():Promise<string>;

export function ReadImage(arg1:string):Promise<imgread.Result>;

export function SaveState(arg1:state.StateData):Promise<void>;
