// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetThumbnail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetThumbnail'](arg1, arg2, arg3);
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function ReadImage(arg1) {
  return window['go']['main']['App']['ReadImage'](arg1);
}

export function SaveState(arg1) {
  return window['go']['main']['App']['SaveState'](arg1);
}
