// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEmptyClassification(arg1) {
  return window['go']['main']['App']['CreateEmptyClassification'](arg1);
}

export function GetImageInfo(arg1) {
  return window['go']['main']['App']['GetImageInfo'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetThumbnail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetThumbnail'](arg1, arg2, arg3);
}

export function LoadClassification(arg1) {
  return window['go']['main']['App']['LoadClassification'](arg1);
}

export function MergeChildSidecars(arg1) {
  return window['go']['main']['App']['MergeChildSidecars'](arg1);
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function PreviewChildSidecars(arg1) {
  return window['go']['main']['App']['PreviewChildSidecars'](arg1);
}

export function ReadImage(arg1) {
  return window['go']['main']['App']['ReadImage'](arg1);
}

export function SaveClassification(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveClassification'](arg1, arg2, arg3);
}

export function SaveState(arg1) {
  return window['go']['main']['App']['SaveState'](arg1);
}

export function UpdateClassificationEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateClassificationEntry'](arg1, arg2, arg3);
}
