// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDuplicates(arg1, arg2) {
  return window['go']['main']['App']['CheckDuplicates'](arg1, arg2);
}

export function CreateEmptyClassification(arg1) {
  return window['go']['main']['App']['CreateEmptyClassification'](arg1);
}

export function DeleteImage(arg1, arg2) {
  return window['go']['main']['App']['DeleteImage'](arg1, arg2);
}

export function DismissDuplicatePair(arg1, arg2, arg3) {
  return window['go']['main']['App']['DismissDuplicatePair'](arg1, arg2, arg3);
}

export function GetImageInfo(arg1) {
  return window['go']['main']['App']['GetImageInfo'](arg1);
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetThumbnail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetThumbnail'](arg1, arg2, arg3);
}

export function LoadClassification(arg1) {
  return window['go']['main']['App']['LoadClassification'](arg1);
}

export function LogEvent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LogEvent'](arg1, arg2, arg3, arg4);
}

export function MergeChildSidecars(arg1) {
  return window['go']['main']['App']['MergeChildSidecars'](arg1);
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function PreviewChildSidecars(arg1) {
  return window['go']['main']['App']['PreviewChildSidecars'](arg1);
}

export function ReadImage(arg1) {
  return window['go']['main']['App']['ReadImage'](arg1);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function SaveClassification(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveClassification'](arg1, arg2, arg3);
}

export function SaveState(arg1) {
  return window['go']['main']['App']['SaveState'](arg1);
}

export function StartFolderWatch(arg1) {
  return window['go']['main']['App']['StartFolderWatch'](arg1);
}

export function StopFolderWatch() {
  return window['go']['main']['App']['StopFolderWatch']();
}

export function UpdateClassificationEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateClassificationEntry'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
