// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {classification} from '../models';
import {imgread} from '../models';
import {settings} from '../models';
import {state} from '../models';
import {thumb} from '../models';

export function CreateEmptyClassification(arg1:string):Promise<classification.SaveOutput>;

export function DeleteImage(arg1:string,arg2:string):Promise<void>;

export function GetImageInfo(arg1:string):Promise<imgread.Info>;

export function GetLogPath():Promise<string>;

export function GetSettings():Promise<settings.SettingsData>;

export function GetState():Promise<state.StateData>;

export function GetThumbnail(arg1:string,arg2:number,arg3:string):Promise<thumb.Result>;

export function LoadClassification(arg1:string):Promise<classification.LoadResult>;

export function LogEvent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function MergeChildSidecars(arg1:string):Promise<classification.SaveOutput>;

export function OpenFolderDialog():Promise<string>;

export function PreviewChildSidecars(arg1:string):Promise<classification.MergePreview>;

export function ReadImage(arg1:string):Promise<imgread.Result>;

export function ResetSettings():Promise<settings.SettingsData>;

export function SaveClassification(arg1:string,arg2:Array<classification.Entry>,arg3:number):Promise<classification.SaveOutput>;

export function SaveState(arg1:state.StateData):Promise<void>;

export function StartFolderWatch(arg1:string):Promise<void>;

export function StopFolderWatch():Promise<void>;

export function UpdateClassificationEntry(arg1:string,arg2:classification.Entry,arg3:number):Promise<classification.SaveOutput>;

export function UpdateSettings(arg1:settings.SettingsData):Promise<settings.SettingsData>;
